version: '3'
services:
  fastapi:
    # Путь до Dockerfile
    build: .
    # Имя для создаваемого контейнера
    container_name: short
    
    volumes:
      - ./app/:/app
          # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "8000:7800"
